bit-bots/humanoid_league_misc

humanoid_league_team_communication/src/humanoid_league_team_communication/team_communication.cpp

This pull request closes #1.
It is tested on two computers.

send no data when in Penalty Animation or Picked up

---

humanoid_league_game_controller/src/humanoid_league_game_controller/gamestate.py
humanoid_league_game_controller/src/humanoid_league_game_controller/receiver.py

Add functionallity to react on free kick and similar statuses, fix some bugs

gamecontroller: add free kick etc movements, bugfixes

---

humanoid_league_game_controller/src/humanoid_league_game_controller/receiver.py

This pull request adds the secondary state PENALTYSHOOT to be able to control when the robot is allowed to move during penalty shootout.

Penalty shoot added to game controller

---

humanoid_league_map_generator/generate_maps.py

generates different maps for lines, field boundary, goal posts and the different field features (corners, tcrossings and crosses)

generates likelihood field models for field features for localization

---

humanoid_league_transform/src/humanoid_league_transform/transformer.py

Add `Field_Boundary_In_Image` instead of `Obstacle_In_Image`.

Add correct message type

---

humanoid_league_team_communication/config/team_communication_config.yaml
humanoid_league_transform/config/transformer.yaml
humanoid_league_transform/src/humanoid_league_transform/ball_tester.py
humanoid_league_transform/src/humanoid_league_transform/tf_world.py
humanoid_league_transform/src/humanoid_league_transform/transformer.py

Rename the ball topic to balls. See issue bit-bots/bitbots_vision#66.
Do not merge before the others are merged.

Balls instead of ball

---

humanoid_league_game_controller/scripts/sim_gamestate.py
humanoid_league_game_controller/src/humanoid_league_game_controller/receiver.py

this fixes https://github.com/bit-bots/humanoid_league_misc/issues/7
I didnt add much comments since the code is very straight forward and does not require much more documentation in my oppinion

game controller: fixed comments

---

humanoid_league_transform/src/humanoid_league_transform/transformer.py

transformer: fix ball transform

---

.github/ISSUE_TEMPLATE/1_bug_report.md
.github/ISSUE_TEMPLATE/2_feature_request.md
.github/ISSUE_TEMPLATE/3_need_help.md
.github/pull_request_template.md
humanoid_league_game_controller/package.xml
humanoid_league_game_controller/src/humanoid_league_game_controller/receiver.py

A publisher to publish the information if a connection to the game_controller exists as requested in #24 was added.
#24

game_controller: game_controller_connected publisher added

---

humanoid_league_map_generator/generate_maps.py
humanoid_league_transform/package.xml
humanoid_league_transform/src/humanoid_league_transform/ball_tester.py
humanoid_league_transform/src/humanoid_league_transform/goal_tester.py
humanoid_league_transform/src/humanoid_league_transform/line_tester.py
humanoid_league_transform/src/humanoid_league_transform/lineviz.py
humanoid_league_transform/src/humanoid_league_transform/tf_world.py
humanoid_league_transform/src/humanoid_league_transform/transformer.py

This pull request updates all shebangs to python3 as we will discuss in our weekly.

Update shebangs to python3

---

Jenkinsfile
humanoid_league_game_controller/CMakeLists.txt
humanoid_league_game_controller/package.xml
humanoid_league_speaker/CMakeLists.txt
humanoid_league_speaker/package.xml
humanoid_league_team_communication/CMakeLists.txt
humanoid_league_team_communication/include/humanoid_league_team_communication/team_communication.h
humanoid_league_team_communication/package.xml
humanoid_league_team_communication/src/humanoid_league_team_communication/team_communication.cpp
humanoid_league_transform/CMakeLists.txt
humanoid_league_transform/package.xml

This adds a Jenkinsfile to the repo and activates docs for humanoid_league_speaker, humanoid_league_transform, humanoid_league_game_controller and humanoid_league_team_communication.

Add Jenkinsfile and activate docs

---

humanoid_league_speaker/cfg/speaker_params.cfg

change shebang and or package.xml to work with python3
- ~~[ ] Update package version~~
- ~~[ ] Run linters~~
- ~~[ ] Write documentation~~
- ~~[x] Test on your machine~~

python 3 compatability

---

humanoid_league_transform/src/humanoid_league_transform/transformer.py

Transformer: Add binning support

---

humanoid_league_transform/config/transformer.yaml
humanoid_league_transform/src/humanoid_league_transform/transformer.py

Add check if the footpoint is not in the bottom area of the image.
#28

Transformer: Drop out of image goal posts

---

humanoid_league_transform/src/humanoid_league_transform/transformer.py

- Clip the binning value at one.Otherwise division by zero errors would be possible

Transformer: Cap binning to min 1

---

humanoid_league_game_controller/package.xml
humanoid_league_game_controller/scripts/sim_gamestate.py

The secondary game states and the secondaryStateTeam variable of the GameState message are added to the sim_gamestate script.

Game Controller Sim: add secondary game state and team

---

humanoid_league_transform/package.xml
humanoid_league_transform/src/humanoid_league_transform/ball_tester.py
humanoid_league_transform/src/humanoid_league_transform/line_tester.py
humanoid_league_transform/src/humanoid_league_transform/transformer.py

This PR fixes the test scripts that were still on python 2 and fixes the loop at startup which checks whether camera_info messages are received.

transformer: small fixes

---

humanoid_league_transform/config/transformer.yaml
humanoid_league_transform/src/humanoid_league_transform/transformer.py

- Project image masks as point clouds onto the field plane
- Optimize the transformer speed using NumPy optimizations
Closes #38

Project masks in the transformer

---

humanoid_league_map_generator/generate_maps.py

this pr creates an option to specify an output folder and optionally a ros package
If no ros package is specified, the rospkg package is not imported, removing the ros dependency 
#60 
- ~~[ ] Update package version~~
- ~~[ ] Run `catkin build`~~
- ~~[ ] Create issues for future work~~
- ~~[ ] Test on the robot~~

map generator output folder

---

humanoid_league_game_controller/config/game_controller_settings.yaml
humanoid_league_game_controller/launch/game_controller.launch
humanoid_league_game_controller/src/humanoid_league_game_controller/receiver.py
humanoid_league_speaker/config/speaker_config.yaml
humanoid_league_speaker/launch/speaker.launch
humanoid_league_speaker/src/humanoid_league_speaker/speaker.py
humanoid_league_team_communication/config/team_communication_config.yaml
humanoid_league_team_communication/launch/team_comm.launch
humanoid_league_team_communication/scripts/TeamCommTest.py
humanoid_league_team_communication/src/humanoid_league_team_communication/team_communication.cpp

namespaces for game_controller, speaker and teamcomm

---

Jenkinsfile
humanoid_league_game_controller/.rdmanifest
humanoid_league_game_controller/rosdoc.yaml
humanoid_league_speaker/.rdmanifest
humanoid_league_speaker/rosdoc.yaml
humanoid_league_team_communication/.rdmanifest
humanoid_league_team_communication/rosdoc.yaml
humanoid_league_transform/.rdmanifest
humanoid_league_transform/rosdoc.yaml

update CI config and add `.rdmanifest` files

---

humanoid_league_team_communication/.rdmanifest
humanoid_league_team_communication/package.xml

Fix CI for humanoid_league_misc

---

humanoid_league_map_generator/generate_maps.py

Add goal back area to generate maps script
Add argument to change the amount of blurring
https://github.com/bit-bots/bitbots_navigation/issues/110
~- [ ] Run `catkin build`~
~- [ ] Write documentation~
~- [ ] Create issues for future work~
~- [ ] Test on the robot~

Generate maps: Goal back area and variable blur

---

humanoid_league_transform/config/transformer.yaml
humanoid_league_transform/src/humanoid_league_transform/transformer.py

* Add it also the the obstacles not only to the goalposts
#76

Add the ability to obstacles that end at the bottom of the image

---

humanoid_league_game_controller/src/humanoid_league_game_controller/gamestate.py
humanoid_league_game_controller/src/humanoid_league_game_controller/receiver.py

Update the structure of the udp message from the game controller to the current upstream because our version is outdated.

Update game controller message from upstream

---

humanoid_league_team_communication/CMakeLists.txt
humanoid_league_team_communication/src/humanoid_league_team_communication/team_communication.cpp

Same as bit-bots/bitbots_motion#256.

use -Wall in team communication

---

humanoid_league_speaker/src/humanoid_league_speaker/speaker.py

https://github.com/bit-bots/bitbots_misc/pull/122

change to new rate implementation

---

humanoid_league_transform/config/transformer.yaml

This helps with performance in the localization and stuff

Add lower res for the point clouds.

---

humanoid_league_game_controller/scripts/sim_gamestate.py
humanoid_league_game_controller/src/humanoid_league_game_controller/receiver.py

fix secondary gamestate

---

humanoid_league_game_controller/scripts/sim_gamestate.py

Follow-up on bit-bots/humanoid_league_msgs#28, closes #88.

Remove old message from sim_gamestate

---

humanoid_league_game_controller/src/humanoid_league_game_controller/receiver.py

Needs https://github.com/bit-bots/humanoid_league_msgs/pull/32

fixes missing information in game state

---

humanoid_league_team_communication/config/team_communication_config.yaml
humanoid_league_team_communication/src/humanoid_league_team_communication/humanoid_league_team_communication.py

send time to ball through team comm

---

humanoid_league_transform/config/transformer.yaml

Add adult ball size

---

humanoid_league_team_communication/launch/team_comm_test_marker.launch
humanoid_league_team_communication/scripts/teamcomm_test_marker.py

Fix team comm test marker script

---

humanoid_league_speaker/config/speaker_config.yaml

increase speaker volumne

---

humanoid_league_game_controller/.gitignore
humanoid_league_game_controller/config/game_controller.yaml.example
humanoid_league_game_controller/humanoid_league_game_controller/receiver.py
humanoid_league_game_controller/launch/game_controller.launch
humanoid_league_game_controller/package.xml
humanoid_league_game_controller/scripts/sim_gamestate.py
humanoid_league_game_controller/setup.py

- GameController now uses parameter_blackboard for game settings
- `sim_gamestate` is now in ROS2

Game controller use param blackboard and ros2ify sim gamestate

---

humanoid_league_team_communication/humanoid_league_team_communication/humanoid_league_team_communication.py

Team comm: Fix Topics

---

humanoid_league_team_communication/config/team_communication_config.yaml
humanoid_league_team_communication/humanoid_league_team_communication/humanoid_league_team_communication.py

Add thread to spin.
Decrease frequency.

Team comm: create thread to spin

---

humanoid_league_speaker/config/speaker_config.yaml
humanoid_league_speaker/humanoid_league_speaker/speaker.py
humanoid_league_speaker/launch/speaker.launch

- Use mimic3 neural tts instead of espeak
- Refactor speaker node
- Due to limitations of `aplay` the system volume needs to be used.
#129 
https://github.com/bit-bots/bitbots_motion/pull/388

Use mimic for speaker

---

humanoid_league_team_communication/humanoid_league_team_communication/communication.py

Fix typo in team comm: communication

---

humanoid_league_game_controller/scripts/sim_gamestate.py

Set kickoff in sim gamestate script

---

humanoid_league_map_generator/generate_maps.py

The current default leads to a gray image

Better default for blur

---

humanoid_league_game_controller/package.xml
humanoid_league_speaker/package.xml
humanoid_league_team_communication/package.xml

to allow for new features like conditional depends accoring to rep [0149].
We use this to differentiate between dependencies required on robots and in
the simulation.
[149]: https://www.ros.org/reps/rep-0149.html

fix(package.xml): upgrade to version 3

---

humanoid_league_game_controller/scripts/sim_gamestate.py

- cleanup of KeyboardInterrupt handling
- cleanup of old namespace stuff
- black

Cleanup sim_gamestate.py
